AWSTemplateFormatVersion: 2010-09-09
Description: |
  This template is used to deploy a simple lambda functions

Parameters:
  Architectures:
    Description: set architecture that the function supports
    Type: String
    Default: x86_64

Resources:
  Lambda:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
          - x86_64
      Description: Lambda function for Data Migration
      FunctionName: !Sub "rkp-${EnvironmentName}-messenger-lambda"
      Runtime: dotnet8
      CodeUri: ./
      Timeout: 120
      MemorySize: 256
      Handler: "index.handler"
      Role: !Sub "arn:aws:iam::${AWS::AccountId}:role/lambs3"
      Environment: 
        Variables: 
          FILE_CACHE_PATH: "/tmp"
      TracingConfig: 
        Mode: PassThrough
      EphemeralStorage: 
        Size: 512
      VpcConfig:
        SecurityGroupIds:
          - !Ref APPSecuritygroup
          - !Ref ConnectionsSecurityGroup
        SubnetIds:
          - !Ref SVCSubnet12a
          - !Ref SVCSubnet22b

  LambdaUrl:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: AWS_IAM  # Change to AWS_IAM if you want to restrict access
      TargetFunctionArn: !GetAtt Lambda.Arn          
      InvokeMode: RESPONSE_STREAM

  LambdaFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunctionUrl
      FunctionName: !Ref Lambda
      Principal: "*"
      FunctionUrlAuthType: AWS_IAM  # Change this if restricting access

Outputs:
  LambdaFunctionUrl:
    Description: "Lambda Function URL"
    Value: !GetAtt LambdaUrl.FunctionUrl