AWSTemplateFormatVersion: 2010-09-09
Description: |
  This template is used to deploy a simple RDS Postgress

Parameters:
  Region:
    Description: An environment name that is prefixed to resource names
    Type: String

  DBInstanceID:
    Default: mydbinstance
    Description: My database instance
    Type: String
    MinLength: '1'
    MaxLength: '63'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: >-
      Must begin with a letter and must not end with a hyphen or contain two
      consecutive hyphens.

  DBName:
    Default: mydb
    Description: My database
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters.

  DBInstanceClass:
    #Default: db.m5.large
    Description: DB instance type
    Type: String
    ConstraintDescription: Must select a valid DB instance type.
  
  Engine:
    Default: postgres
    Description: DB Engine Type
    Type: String
    ConstraintDescription: Must select a valid DB Engine.
  
  EngineVersion:
    #Default: 
    Description: DB Engine 
    Type: String
    ConstraintDescription: Must select a valid DB Engine version.
    

  DBAllocatedStorage:
    #Default: '50'
    Description: The size of the database (GiB)
    Type: Number
    MinValue: '20'
    MaxValue: '65536'
    ConstraintDescription: must be between 20 and 65536 GiB.

  DBUsername:
    NoEcho: 'true'
    Description: Username for MySQL database access
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.

  DBPassword:
    NoEcho: 'true'
    Description: Password MySQL database access
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.

  LicenseModel:
    Default: postgresql-license
    Description: DB License Model Type
    Type: String
######################## security group ######################
Resources:
  DBSecuritygroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG to test RDS
      VpcId: vpc-07a9ee719eb94c978
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: "-1"
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: Allow-in-All

#################### DB Subnet Group ##############################
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "Subnets for RDS database"
      SubnetIds:
        - !Ref DBSubnet12bCIDR
        - !Ref DBSubnet12aCIDR
      Tags:
        - Key: Name
          Value: "MyDBSubnetGroup"


######################## RDS ######################################
  RDSDBInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceIdentifier: !Sub vywus-${EnvironmentName}-messenger-pgsql
      AllocatedStorage: !Ref DBAllocatedStorage
      #AutomaticBackupReplicationRegion: !Ref AutomaticBackupReplicationRegion
      BackupRetentionPeriod: 7
      DBInstanceClass: !Ref DBInstanceClass
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      Engine: !Ref Engine
      EngineVersion: !Ref EngineVersion
      #Iops: 1000
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword 
      StorageType: gp3
      AutoMinorVersionUpgrade: false
#     KmsKeyId:
      DBSubnetGroupName: !Ref DBSubnetGroup
      LicenseModel: !Ref LicenseModel
      MultiAZ: false
      EnablePerformanceInsights: true
      PerformanceInsightsRetentionPeriod: 7
      EngineLifecycleSupport: open-source-rds-extended-support-disabled
      StorageEncrypted: true
      MaxAllocatedStorage: 50
      VPCSecurityGroups:
        - !Ref DBSecuritygroup
      Tags:
        - Key: Name
          Value: !Join ['', ["sample-","-web-"]]
  