AWSTemplateFormatVersion: 2010-09-09
Description: >

Parameters:
  TopicName:
    Default: samplefortest
    Description: Enter the topic TopicName
    Type: String

  # ApplicationName: 
  #   Default: Sampleapp
  #   Description: "AWS Elastic Beanstalk .netcore Application"
  #   Type: String

  # EnvironmentName:
  #   Default: develop 
  #   Description: "AWS Elastic Beanstalk .netcore Application Env name"
  #   Type: String

  Endpoint:
    Default: saba@gmail.com
    Description: "This value as the prefix for the CNAME in your Elastic Beanstalk environment URL"
    Type: String
  Endpoint2:
    Default: shabai28@gmail.com
    Description: "This value as the prefix for the CNAME in your Elastic Beanstalk environment URL"
    Type: String

Resources:
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Ref TopicName
  SNSSubscription:
        Type: "AWS::SNS::Subscription"
        Properties:
            TopicArn: !Ref SNSTopic
            Endpoint: !Ref Endpoint
            Protocol: "email"
            Region: !Ref AWS::Region
  SNSSubscription2:
        Type: "AWS::SNS::Subscription"
        Properties:
            TopicArn: !Ref SNSTopic
            Endpoint: !Ref Endpoint2
            Protocol: "email"
            Region: !Ref AWS::Region
 