AWSTemplateFormatVersion: 2010-09-09
Description: |
  This template deploys an RDS PostgreSQL instance with secrets stored in AWS Secrets Manager.
  
Parameters:
  Instancetype: 
    Description: Instance type stored in SSM
    Type: String
    Default: /vywus/msgr/master/env/instancetype

  DBPasswordSSMPath:
    Description: Path to the database password stored in SSM Parameter Store
    Type: String
    Default: /vywus/msgr/master/env/db-password  # Ensure this is a SecureString parameter

  Env:
    Description: Env name
    Type: String
    Default: Dev 

Resources:
  GetSSMParameterFunction:   # Lambda Function to Fetch SSM SecureString Value
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.lambda_handler
      Runtime: python3.9
      Timeout: 10
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          import json
          import boto3
          import cfnresponse

          def lambda_handler(event, context):
              ssm = boto3.client('ssm')
              response_data = {}
              
              try:
                  if event['RequestType'] in ['Create', 'Update']:
                      param_name = event['ResourceProperties']['SSMParameterName']
                      response = ssm.get_parameter(Name=param_name, WithDecryption=True)
                      response_data['ParameterValue'] = response['Parameter']['Value']
                  
                  cfnresponse.send(event, context, cfnresponse.SUCCESS, response_data)
              except Exception as e:
                  cfnresponse.send(event, context, cfnresponse.FAILED, {"Error": str(e)})
  
  LambdaExecutionRole: # IAM Role for Lambda
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: SSMReadSecretsPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:GetParameters
                  - ssm:GetParameterHistory
                  - secretsmanager:GetSecretValue
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  # Custom Resource to Fetch SSM SecureString Value for DB Password
  FetchDBPassword:
    Type: Custom::FetchSSMParameter
    Properties:
      ServiceToken: !GetAtt GetSSMParameterFunction.Arn
      SSMParameterName: !Ref DBPasswordSSMPath

  # Custom Resource to Fetch SSM SecureString Value for Instancetype
  FetchInstype:
    Type: Custom::FetchSSMParameter
    Properties:
      ServiceToken: !GetAtt GetSSMParameterFunction.Arn
      SSMParameterName: !Ref Instancetype

  # Store SSM SecureString Value into AWS Secrets Manager
  MySecretA:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub "Mysecret-${Env}"
      Description: "This secret references a password stored in SSM SecureString."
      SecretString:
        Fn::Sub:
          - '{"username": "test-user", "password": "${DBPassword}", "instancetype": "${Instype}"}'
          - {
              "DBPassword": !GetAtt FetchDBPassword.ParameterValue,
              "Instype": !GetAtt FetchInstype.ParameterValue
            }
      Tags:
        - Key: AppName
          Value: AppA

  WebAppInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0d5eff06f840b45e9  # ImageID valid only in us-east-1 region
      InstanceType: !Join ['', ['{{resolve:secretsmanager:', !Ref MySecretA, ':SecretString:instancetype}}' ]] # Uses the value from Secrets Manager
      KeyName: nv-win # Ensure this key pair exists in your AWS account
      SecurityGroups:
        - default
      Tags:
        - Key: Name
          Value: WebAppInstance